### ISSUE TITLE
分支master-1.2.x 提示maven打包失败 

### ISSUE THREAD

**Issue by radishlee** [changmingxie/tcc-transaction#232]
[INFO] tcc-transaction-http-redpacket ..................... SUCCESS [  4.059 s]
[INFO] tcc-transaction-server ............................. FAILURE [  3.659 s]
[INFO] tcc-transaction-server-sample ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:13 min
[INFO] Finished at: 2018-12-29T16:12:22+08:00
[INFO] Final Memory: 150M/668M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.1.1:war (default-war) on project tcc-transaction-server: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.1.1:war failed: basedir D:\job\git\tcc-transaction\tcc-transaction-server\src\main\config\dev does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.1.1:war (default-war) on project tcc-transaction-server: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.1.1:war failed: basedir D:\job\git\tcc-transaction\tcc-transaction-server\src\main\config\dev does not exist
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)

显示少配置文件 请问作者是怎么用的

**Comment by radishlee** [comment]
master分支可编译通过

**Comment by radishlee** [comment]
艹 把master分支的conf文件夹拷过来即可 艹
