### ISSUE TITLE
tcc-transaction-http-order报错,  @UniqueIdentity 取值为null时没有处理

### ISSUE THREAD

**Issue by ahexian** [changmingxie/tcc-transaction#257]
请求地址: http://127.0.0.1:8080/tcc-transaction-http-order/user/2000/shop/1/product/1/confirm 

经调试后发现是: 
  org.mengyun.tcctransaction.interceptor.CompensableMethodContext.getUniqueIdentity() 这里在取 @UniqueIdentity 标记的值,
  而在目标方法里面: 没有标记 @UniqueIdentity 注解
   @Compensable(confirmMethod = "confirmMakePayment", cancelMethod = "cancelMakePayment", asyncConfirm = true)
   @Transactional
   public void makePayment(Order order, BigDecimal redPacketPayAmount, BigDecimal capitalPayAmount) {
	  ......
   }
   
最后在 org.mengyun.tcctransaction.api.TransactionXid 类的构造方法中没有判断 uniqueIdentity 为null时的处理, 最终报错

	public TransactionXid(Object uniqueIdentity) {
        this.globalTransactionId = uuidToByteArray(UUID.nameUUIDFromBytes("UniqueIdentity".getBytes()));

        UUID branchUuid = null;

        if (uniqueIdentity instanceof UUID) {
            branchUuid = (UUID) uniqueIdentity;
        } else {
            try {
                branchUuid = UUID.fromString(uniqueIdentity.toString());
            } catch (IllegalArgumentException e) {

                byte[] bytes = uniqueIdentity.toString().getBytes();

                if (bytes.length > 16) {
                    throw new IllegalArgumentException("UniqueIdentify is illegal, the value is :" + uniqueIdentity.toString());
                }

                branchUuid = UUID.nameUUIDFromBytes(bytes);
            }
        }

        this.branchQualifier = uuidToByteArray(branchUuid);
    }
   

后台报错堆栈: 
java.lang.NullPointerException
	at org.mengyun.tcctransaction.api.TransactionXid.<init>(TransactionXid.java:45)
	at org.mengyun.tcctransaction.Transaction.<init>(Transaction.java:60)
	at org.mengyun.tcctransaction.TransactionManager.begin(TransactionManager.java:41)
	at org.mengyun.tcctransaction.interceptor.CompensableTransactionInterceptor.rootMethodProceed(CompensableTransactionInterceptor.java:75)
	at org.mengyun.tcctransaction.interceptor.CompensableTransactionInterceptor.interceptCompensableMethod(CompensableTransactionInterceptor.java:49)
	at org.mengyun.tcctransaction.interceptor.CompensableTransactionAspect.interceptCompensableMethod(CompensableTransactionAspect.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
	at org.mengyun.tcctransaction.sample.http.order.service.PaymentServiceImpl$$EnhancerBySpringCGLIB$$4a78a9df.makePayment(<generated>)
	at org.mengyun.tcctransaction.sample.http.order.service.PlaceOrderServiceImpl.placeOrder(PlaceOrderServiceImpl.java:40)
	at org.mengyun.tcctransaction.sample.http.order.web.controller.OrderController.placeOrder(OrderController.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:685)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:919)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:851)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ahexian** [comment]
解决了:

调用方类: org.mengyun.tcctransaction.sample.http.order.service.PlaceOrderServiceImpl 的 placeOrder 方法:
位置: H:\soft\sts\TCC1.2\tcc-transaction-master-1.2.x\tcc-transaction-tutorial-sample\tcc-transaction-http-sample\tcc-transaction-http-order\src\main\java\org\mengyun\tcctransaction\sample\http\order\service\PlaceOrderServiceImpl.java

public String placeOrder(long payerUserId, long shopId, List<Pair<Long, Integer>> productQuantities, BigDecimal redPacketPayAmount) {
   ......
   **String merchantOrderNo = order.getMerchantOrderNo();**
            paymentService.makePayment(**merchantOrderNo,** order, redPacketPayAmount,    order.getTotalAmount().subtract(redPacketPayAmount));
   ......
}



org.mengyun.tcctransaction.sample.http.order.service.PaymentServiceImpl类(被调用方)的
位置: H:\soft\sts\TCC1.2\tcc-transaction-master-1.2.x\tcc-transaction-tutorial-sample\tcc-transaction-http-sample\tcc-transaction-http-order\src\main\java\org\mengyun\tcctransaction\sample\http\order\service\PaymentServiceImpl.java

@Compensable(confirmMethod = "confirmMakePayment", cancelMethod = "cancelMakePayment", asyncConfirm = true)
    @Transactional
    public void **makePayment**(**@UniqueIdentity String orderNo,** Order order, BigDecimal redPacketPayAmount, BigDecimal capitalPayAmount) {
     ......
}

public void **confirmMakePayment**(String orderNo, Order order, BigDecimal redPacketPayAmount, BigDecimal capitalPayAmount) {
     ......
}

public void **cancelMakePayment**(String orderNo, Order order, BigDecimal redPacketPayAmount, BigDecimal capitalPayAmount) {
     ......
}

**Comment by ahexian** [comment]
![图片](https://user-images.githubusercontent.com/13496526/57223739-ac705300-7039-11e9-89f4-5ba24ca9e73b.png)



![图片](https://user-images.githubusercontent.com/13496526/57223697-85b21c80-7039-11e9-9e17-74bc515d295f.png)
