### ISSUE TITLE
红包模块无法启动

### ISSUE THREAD

**Issue by watermelon-w** [changmingxie/tcc-transaction#269]
Caused by: org.mengyun.tcctransaction.repository.TransactionIOException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'IS_DELETE' in 'where clause'
	at org.mengyun.tcctransaction.repository.JdbcTransactionRepository.doFindAllUnmodifiedSince(JdbcTransactionRepository.java:225)
	at org.mengyun.tcctransaction.repository.CachableTransactionRepository.findAllUnmodifiedSince(CachableTransactionRepository.java:89)
	at org.mengyun.tcctransaction.recover.TransactionRecovery.loadErrorTransactions(TransactionRecovery.java:41)
	at org.mengyun.tcctransaction.recover.TransactionRecovery.startRecover(TransactionRecovery.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:312)
	... 3 more

**Comment by 18818018912** [comment]
www.java52.com  提供tcc-transaction的源码解析视频
